spring:
  datasource:
    url: jdbc:mysql://localhost/exceltask?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  #设置上传文件的大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  config-location:
    classpath: mybatis-config.xml
